name: flutter_networking_demo
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  #sdk: ^3.5.0  
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  chopper: ^5.0.2
  provider: ^6.1.3

dev_dependencies:
  flutter_test:
    #sdk: flutter
    sdk: ^3.5.0

flutter:
  uses-material-design: true
